# Generated by Django 5.2.4 on 2025-07-27 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('IdOperacao', models.AutoField(primary_key=True, serialize=False)),
                ('Parametros', models.CharField(max_length=100)),
                ('Resultado', models.CharField(max_length=100)),
                ('DtaInclusao', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
